### ISSUE TITLE
Failed to load save.

### ISSUE THREAD

**Issue by NEGU93** [linuslin0/ACST#80] opened 2022-03-15 19:59 UTC
I fails to open my saved games. I selected detect for Decryption ID and selected a saved game for the Encryption ID.

The error message is not very helpful

```
-> E:\HardDiskDrive\Programas\Juegos\Saves\Black Flag\save3dmgames\1.save

-> Processing "1.save" ... 
Failed to load save.

Execution time: 0.0001625
```

**Comment by NEGU93** [comment] 2022-03-15 21:21
[Here](https://github.com/linuslin0/ACST/files/8257242/1.save.csv) the saved file I want to convert (change the name to `1.save`)

**Comment by NEGU93** [comment] 2022-03-15 21:24
Another example: [5.save.csv](https://github.com/linuslin0/ACST/files/8257261/5.save.csv)

**Comment by linuslin0** [comment] 2022-03-16 14:19
This tool only supports saves from legit game copy.
If you want to convert those saves please upload the complete save folder, along with the ini file. Also the test save you were using to for the Encryption ID.

**Comment by NEGU93** [comment] 2022-03-17 21:11
I do have the `.ini` file. But how can I select the full folder? It only lets me select files and not folders.

Just to check I am doing the rest correct:

- For encryption, I have to select a generated save game from the Ubisoft connect game I want to convert to? Meaning the first `1.save` that gets created just by opening the game? Decryption I do auto-detect and I do select AC Black Flag.

**Comment by linuslin0** [comment] 2022-03-18 02:26
Your steps are correct. The problem is the saves you want to convert are not from legit game copy and they are not supported by this tool. As I mentioned earlier, please upload the entire save folder (in a zip archive) so I could help you convert them.

**Comment by NEGU93** [comment] 2022-03-18 08:29
Oh sorry, I did not understand that. [Here](https://github.com/linuslin0/ACST/files/8302827/save3dmgames.zip) is the file.

**Comment by linuslin0** [comment] 2022-03-19 00:35
No worries.
OK so the 1.save and 2.save are empty actually (you could check with any hex editor). I did converted the other 3 files:
[ACBF_converted.zip](https://github.com/linuslin0/ACST/files/8308287/ACBF_converted.zip)

**Comment by NEGU93** [comment] 2022-03-19 09:08
You are my hero. 
I still can't play them but maybe that is a question for Ubisoft itself I think. It is weird now that I realize that Ubisoft creates a `1.save.upload` also which I don't have.
In any case, thank you a lot, you can close this issue.

**Comment by linuslin0** [comment] 2022-03-31 20:06
np. closing this issue.

**Closed by linuslin0** 2022-03-31 20:06 UTC

**Comment by Fredy1255** [comment] 2024-07-11 11:14
Hello can you help me linuslin0 I have same problem i have saves from non legit game and want to convert them to legit version here is folder with saves and test save. Thank you for your help. 
[save3dmgames.zip](https://github.com/user-attachments/files/16175850/save3dmgames.zip)
[testsave.zip](https://github.com/user-attachments/files/16175870/testsave.zip)

**Comment by linuslin0** [comment] 2024-07-14 00:31
> Hello can you help me linuslin0 I have same problem i have saves from non legit game and want to convert them to legit version here is folder with saves and test save. Thank you for your help. [save3dmgames.zip](https://github.com/user-attachments/files/16175850/save3dmgames.zip) [testsave.zip](https://github.com/user-attachments/files/16175870/testsave.zip)

Please try with these converted saves. 
[ACBF_converted.zip](https://github.com/user-attachments/files/16209807/ACBF_converted.zip)

**Comment by Fredy1255** [comment] 2024-07-14 08:16
> > Hello can you help me linuslin0 I have same problem i have saves from non legit game and want to convert them to legit version here is folder with saves and test save. Thank you for your help. [save3dmgames.zip](https://github.com/user-attachments/files/16175850/save3dmgames.zip) [testsave.zip](https://github.com/user-attachments/files/16175870/testsave.zip)
> 
> Please try with these converted saves. [ACBF_converted.zip](https://github.com/user-attachments/files/16209807/ACBF_converted.zip)

Thank you very much save files work. Good job man.

**Comment by zmo7mad** [comment] 2024-11-18 15:58
hey  linuslin0 , im facing the same issue .. i have a non legit copy of ac mirage and i want your help converting them into legit copy's
[save.zip](https://github.com/user-attachments/files/17803124/save.zip)

**Comment by Fearmor** [comment] 2024-11-20 03:36
> > Hello can you help me linuslin0 I have same problem i have saves from non legit game and want to convert them to legit version here is folder with saves and test save. Thank you for your help. [save3dmgames.zip](https://github.com/user-attachments/files/16175850/save3dmgames.zip) [testsave.zip](https://github.com/user-attachments/files/16175870/testsave.zip)
> 
> Please try with these converted saves. [ACBF_converted.zip](https://github.com/user-attachments/files/16209807/ACBF_converted.zip)

Hello Linsulin0, if you could be so kind could help me as well with Unity saves? Its from Reloaded..
[AcUnitySv.zip](https://github.com/user-attachments/files/17824403/AcUnitySv.zip)

**Comment by linuslin0** [comment] 2024-11-21 02:16
> hey linuslin0 , im facing the same issue .. i have a non legit copy of ac mirage and i want your help converting them into legit copy's [save.zip](https://github.com/user-attachments/files/17803124/save.zip)

It's an empty archive.

**Comment by linuslin0** [comment] 2024-11-21 02:17
@Fearmor  Please also share a test save from this game on your account.

**Comment by Fearmor** [comment] 2024-11-21 12:26
Sure, thank you very much!
[720.zip](https://github.com/user-attachments/files/17845563/720.zip)

**Comment by linuslin0** [comment] 2024-11-22 02:02
> @linuslin0 Sure, thank you very much! [720.zip](https://github.com/user-attachments/files/17845563/720.zip)
[ACUnity.zip](https://github.com/user-attachments/files/17854536/ACUnity.zip)

**Comment by zmo7mad** [comment] 2024-11-22 09:59
oh sorry man i didnt notice i was in a rush , anyways this is the saves file 
[save.zip](https://github.com/user-attachments/files/17868325/save.zip)

**Comment by zmo7mad** [comment] 2024-11-22 10:00
hey uh sorry for that i didnt notice , here is the save file 
[saves.zip](https://github.com/user-attachments/files/17868334/saves.zip)

**Comment by linuslin0** [comment] 2024-11-23 15:46
> hey uh sorry for that i didnt notice , here is the save file 
> 
> [saves.zip](https://github.com/user-attachments/files/17868334/saves.zip)
> 
> 

I don't think those saves came from a normal/release build of this game, even if we bind them to your own account id they won't be able to load by the legit game copy on your account.

**Comment by zmo7mad** [comment] 2024-11-24 17:28
well my game is cracked not that its a legit copy of the game

**Comment by linuslin0** [comment] 2024-11-25 19:48
> well my game is cracked not that its a legit copy of the game

I thought you wanted to use those save in your legit game copy as you mentioned earlier. Also you might want to check in on #172

**Comment by emfaivre** [comment] 2025-01-12 04:35
Hello can you help me with my ac unity save ? please 
[720.zip](https://github.com/user-attachments/files/18388132/720.zip)

**Comment by farisfrz** [comment] 2025-04-28 13:11
excuse me, i have the 3dm version since i want to replay the game
but i want to play with 100% saves, i already use from the internet but when i played the game the save is like not detected, no save found
can you help me?

AC 4 Black Flag

**Comment by EkagraTheBeast** [comment] 2025-07-23 06:33
@linuslin0 Please help with my save game of ac4 black flag, its a 100% save i made my self and i really want to keep it 

[save3dmgames.zip](https://github.com/user-attachments/files/21381066/save3dmgames.zip)
